env_name: Blackjack-v1
seed: 123
agent:
  type: MonteCarloAgent
  policy: epsilon
training:
  episodes: 50000
  max_steps_per_episode: 100
  eval_interval: 1000
  eval_episodes: 500
  early_stopping: false
  early_stopping_patience: 1000
  early_stopping_delta: 0.01
  save_best: true
  verbose: false
plot:
  learning_curve_window: 200
  save_path: ../results/montecarlo_learning_curve.png
export:
  policy_csv: ../results/montecarlo_policy.csv
  q_table: ../results/montecarlo_q_table.npy
grid:
  alpha: [0.05, 0.1]
  gamma: [0.90, 0.95]
  epsilon: [0.1]
  policy: ["epsilon", "greedy", "softmax", "decay"]
  episodes: [1000, 2000, 5000]
