env_name: Blackjack-v1
seed: 123
agent:
  type: SARSAAgent
  alpha: 0.1
  gamma: 1.0
  epsilon: 0.05
  decay_rate: 0.0005
training:
  episodes: 50000
  max_steps_per_episode: 100
  eval_interval: 200
  eval_episodes: 200
plot:
  learning_curve_window: 200
  save_path: ../results/sarsa_learning_curve.png
export:
  policy_csv: ../results/sarsa_policy.csv
  q_table: ../results/sarsa_q_table.npy